          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖    
          ▜███▙       ▜███▙  ▟███▛    
           ▜███▙       ▜███▙▟███▛    
            ▜███▙       ▜██████▛    
     ▟█████████████████▙ ▜████▛     ▟▙    
    ▟███████████████████▙ ▜███▙    ▟██▙    
           ▄▄▄▄▖           ▜███▙  ▟███▛    
          ▟███▛             ▜██▛ ▟███▛    
         ▟███▛               ▜▛ ▟███▛    
▟███████████▛                  ▟██████████▙    
▜██████████▛                  ▟███████████▛    
      ▟███▛ ▟▙               ▟███▛    
     ▟███▛ ▟██▙             ▟███▛    
    ▟███▛  ▜███▙           ▝▀▀▀▀    
    ▜██▛    ▜███▙ ▜██████████████████▛    
     ▜▛     ▟████▙ ▜████████████████▛    
           ▟██████▙       ▜███▙    
          ▟███▛▜███▙       ▜███▙    
         ▟███▛  ▜███▙       ▜███▙    
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘[1G[19A[47Croot@nixos
[47C----------
[47COS: NixOS 24.05.20240531.63dacb4 (Uakari) x86_64
[47CHost: KVM/QEMU Standard PC (i440FX + PIIX, 1996) (pc-i440fx-8.1)
[47CKernel: Linux 6.6.32
[47CUptime: 20 mins
[47CPackages: 437 (nix-system)
[47CShell: bash 5.2.26
[47CDisplay (QEMU Monitor): 1280x800 @ 75Hz
[47CTerminal: dumb
[47CCPU: QEMU Virtual version 2.5+ (4) @ 3.79 GHz
[47CGPU: Unknown Device 1111 (VGA compatible)
[47CMemory: 387.68 MiB / 3.83 GiB (10%)
[47CSwap: Disabled
[47CDisk (/): 24.76 MiB / 1.92 GiB (1%) - tmpfs
[47CDisk (/iso): 1.17 GiB / 1.17 GiB (100%) - iso9660 [Read-only]
[47CLocal IP (ens18): 192.168.2.124/24 *
[47CLocale: en_US.UTF-8
[47C
[47C████████████████████████
[47C████████████████████████
Connect with SSH:
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null nixos@192.168.2.124
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
